AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/dummies/**/*'
    - 'gemfiles/**/*'

Rails:
  Enabled: true

LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FileName:
  Exclude:
    - Appraisals

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'